# --- VARIABLES ---

FRONTEND_DIR=frontend
BACKEND_DIR=backend
# Binary name (built inside BACKEND_DIR) and its path from the repo root. Both
# derive from BIN_NAME so build/prod and clean/run-prod stay in sync.
BIN_NAME=auto-dns-webui
OUTPUT_BIN=$(BACKEND_DIR)/$(BIN_NAME)
# Main package path, relative to BACKEND_DIR (the Go module root).
MAIN_PKG=./cmd/auto-dns-webui
# Directory the frontend build is embedded from (see internal/frontend/embed.go's
# `//go:embed dist/*`).
EMBED_DIR=$(BACKEND_DIR)/internal/frontend/dist

# --- TASKS ---

.PHONY: help dev build prod run-prod clean init \
	check lint lint-backend lint-frontend vet typecheck \
	format format-backend format-frontend \
	test test-backend test-frontend test-race test-coverage test-coverage-html

help:
	@echo "Common tasks:"
	@echo "  make dev         - Start Vite + Go backend in dev mode (proxy to Vite)"
	@echo "  make build       - Build Go backend (dev mode, no embed)"
	@echo "  make prod        - Build frontend and backend (with embedded static files)"
	@echo "  make run-prod    - Run the production binary locally"
	@echo "  make clean       - Remove generated build artifacts"
	@echo ""
	@echo "Quality gates (run before every PR):"
	@echo "  make check       - vet + lint + typecheck + test (backend and frontend)"
	@echo "  make lint        - golangci-lint (backend) + eslint (frontend)"
	@echo "  make vet         - go vet (backend)"
	@echo "  make typecheck   - tsc --noEmit (frontend)"
	@echo "  make format      - gofmt/goimports (backend) + prettier (frontend)"
	@echo "  make test        - go test (backend) + frontend unit tests"
	@echo "  make test-race   - go test -race (backend)"
	@echo "  make test-coverage - go test with coverage summary (backend)"

dev:
	@echo "Running dev mode: Vite + Go (with reverse proxy)"
	cd $(FRONTEND_DIR) && npm run dev & \
	cd $(BACKEND_DIR) && go run -tags=dev $(MAIN_PKG)

build:
	@echo "Building Go backend in dev mode..."
	cd $(BACKEND_DIR) && go build -tags=dev -o $(BIN_NAME) $(MAIN_PKG)

prod:
	@echo "Building frontend..."
	npm install --prefix $(FRONTEND_DIR)
	npm run build --prefix $(FRONTEND_DIR)

	@echo "Copying frontend build into the embed directory..."
	mkdir -p $(EMBED_DIR)
	find $(EMBED_DIR) -mindepth 1 ! -name .placeholder -delete 2>/dev/null || true
	cp -r $(FRONTEND_DIR)/dist/. $(EMBED_DIR)/

	@echo "Building Go backend with embedded frontend..."
	cd $(BACKEND_DIR) && go build -o $(BIN_NAME) $(MAIN_PKG)

run-prod: prod
	@echo "Running production binary..."
	./$(BACKEND_DIR)/auto-dns-webui

clean:
	@echo "Cleaning build output..."
	rm -f $(OUTPUT_BIN)
	rm -rf $(FRONTEND_DIR)/dist
	@echo "Clearing embedded frontend build (keeping .placeholder)..."
	find $(EMBED_DIR) -mindepth 1 ! -name .placeholder -delete 2>/dev/null || true

init:
	@echo "Creating .devcontainer/.env with default configuration..."
	@mkdir -p .devcontainer
	@echo "# Auto-DNS WebUI Configuration" > .devcontainer/.env
	@echo "# Generated by make init - modify as needed" >> .devcontainer/.env
	@echo "" >> .devcontainer/.env
	@echo "# Application Configuration" >> .devcontainer/.env
	@echo "AUTO_DNS_WEBUI_APP_HOSTNAME=auto-dns-webui.local" >> .devcontainer/.env
	@echo "" >> .devcontainer/.env
	@echo "# Server Configuration" >> .devcontainer/.env
	@echo "AUTO_DNS_WEBUI_SERVER_PORT=8080" >> .devcontainer/.env
	@echo "" >> .devcontainer/.env
	@echo "# Development Proxy Configuration (for dev mode)" >> .devcontainer/.env
	@echo "AUTO_DNS_WEBUI_SERVER_PROXY_ENABLE=true" >> .devcontainer/.env
	@echo "AUTO_DNS_WEBUI_SERVER_PROXY_HOSTNAME=localhost" >> .devcontainer/.env
	@echo "AUTO_DNS_WEBUI_SERVER_PROXY_PORT=5173" >> .devcontainer/.env
	@echo "" >> .devcontainer/.env
	@echo "# Etcd Configuration" >> .devcontainer/.env
	@echo "AUTO_DNS_WEBUI_ETCD_HOST=etcd" >> .devcontainer/.env
	@echo "AUTO_DNS_WEBUI_ETCD_PORT=2379" >> .devcontainer/.env
	@echo "AUTO_DNS_WEBUI_ETCD_PATH_PREFIX=/skydns" >> .devcontainer/.env
	@echo "AUTO_DNS_WEBUI_ETCD_LOCK_TTL=5.0" >> .devcontainer/.env
	@echo "AUTO_DNS_WEBUI_ETCD_LOCK_TIMEOUT=2.0" >> .devcontainer/.env
	@echo "AUTO_DNS_WEBUI_ETCD_LOCK_RETRY_INTERVAL=0.1" >> .devcontainer/.env
	@echo "" >> .devcontainer/.env
	@echo "# Logging Configuration" >> .devcontainer/.env
	@echo "AUTO_DNS_WEBUI_LOG_LEVEL=INFO" >> .devcontainer/.env
	@echo "Created .devcontainer/.env with default configuration"

# --- QUALITY GATES ---

# Aggregate pre-PR gate. Mirrors docker-coredns-sync's `check` (lint + test),
# extended with go vet and the frontend TypeScript typecheck. Formatting is a
# separate, non-gating target (`make format`).
check: vet lint typecheck test
	@echo "All checks passed."

lint: lint-backend lint-frontend

lint-backend:
	cd $(BACKEND_DIR) && golangci-lint run ./...

lint-frontend:
	npm run lint --prefix $(FRONTEND_DIR)

vet:
	cd $(BACKEND_DIR) && go vet ./...

typecheck:
	npm run typecheck --prefix $(FRONTEND_DIR)

format: format-backend format-frontend

format-backend:
	cd $(BACKEND_DIR) && gofmt -w .
	@if command -v goimports >/dev/null 2>&1; then \
		cd $(BACKEND_DIR) && goimports -w .; \
	else \
		echo "goimports not installed; skipping (install: go install golang.org/x/tools/cmd/goimports@latest)"; \
	fi

format-frontend:
	npm run format --prefix $(FRONTEND_DIR)

test: test-backend test-frontend

test-backend:
	cd $(BACKEND_DIR) && go test ./...

test-frontend:
	npm test --prefix $(FRONTEND_DIR)

test-race:
	cd $(BACKEND_DIR) && go test -race ./...

test-coverage:
	cd $(BACKEND_DIR) && go test -coverprofile=coverage.out ./... && go tool cover -func=coverage.out

test-coverage-html:
	cd $(BACKEND_DIR) && go test -coverprofile=coverage.out ./... && go tool cover -html=coverage.out -o coverage.html
