services:
  etcd-dns-webui:
    build:
      context: ..
      dockerfile: ./Dockerfile
      target: dev
    ports:
      - "${WEBUI_PORT:-8080}:8080"
      - "5173:5173"
    volumes:
      - ..:/workspace
    command: sleep infinity
    env_file:
      - .env
    depends_on:
      - etcd-webui-datastore

  etcd-webui-datastore:
    image: bitnami/etcd:latest
    container_name: etcd-webui-datastore
    hostname: etcd
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd:2380
      - ETCD_INITIAL_CLUSTER=etcd=http://etcd:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
      - ETCD_NAME=etcd
      - HISTFILE=/.shell_history/bash_history
      - HISTSIZE=10000
      - SAVEHIST=10000
    volumes:
      - ./etcd:/bitnami/etcd
      - etcd_history:/.shell_history
    user: root
    networks:
      default:
        aliases:
          - etcd

volumes:
  etcd_history: {}
